rule bankers 
{
    meta:
    description = "Indicates banker / passwd stealer"

	strings:
	
	$pass1 = "PK11_GetInternalKeySlot" fullword wide ascii
	$pass2 = "PK11_FreeSlot" fullword wide ascii
	$pass3 = "PK11SDR_Decrypt" fullword wide ascii
	$pass4 = "PL_Base64Decode" fullword wide ascii
	$pass5 = "#SharedObjects" nocase wide ascii
	$pass6 = "IE:Password-Protected" nocase wide ascii
	$pass7 = "IE AutoComplete" nocase wide ascii
	$pass8 = "POP3 Password2" fullword wide ascii
	$pass9 = "HTTPMail Password2" fullword wide ascii
	$pass10 = "IE Auto Complete" wide ascii
	$pass11 = "AutoComplete Passwords" wide ascii
	$pass12 = "CopyGlyphDataFrom" wide ascii
	$pass14 = "IE Cookies:" nocase wide ascii
	$pass15 = "ie_cookies" nocase wide ascii
	$pass16 = "Macromedia\\Flash Player" wide ascii
	$pass17 = "flashfxp" nocase wide ascii
	$pass18 = "wcx_ftp.ini" nocase wide ascii
	$pass19 = "Total Commander" wide ascii
	$pass20 = "software\\ipswitch\\ws_ftp" nocase wide ascii
	$pass21 = "FAR manager" nocase wide ascii
	$pass22 = "software\\martin prikryl\\winscp 2\\sessions" nocase wide ascii
    $pass23 = "software\\ftpware\\coreftp\\sites" nocase wide ascii
    $pass24 = "smartftp" nocase wide ascii
    $pass25 = "Software\\Microsoft\\Internet Explorer\\IntelliForms\\Storage2" wide ascii
    $pass26 = "\\Ares\\My Shared Folder" wide ascii
    $pass27 = ":String" fullword wide ascii
    $pass28 = "StringIndex" fullword wide ascii
    $pass29 = "e161255a" fullword wide ascii
    $pass30 = "5e7e8100" fullword wide ascii
    $pass31 = "MS IE FTP Passwords" wide ascii
    $pass32 = "IE:AutoComplete" nocase wide ascii
    $pass34 = "wininetcachecredentials" nocase fullword wide ascii
    $pass35 = "inetcomm server passwords" nocase wide ascii
    $pass36 = "IMAP Password2" fullword wide ascii
    $pass37 = "SOFTWARE\\RIT\\The Bat" nocase wide ascii
    $pass38 = "Coffee Cup" nocase wide ascii
    $pass39 = "TransSoft Ltd\\FTP Control 4" nocase wide ascii
    $pass3a = "ControllFTP" nocase fullword wide ascii
    $pass3b = "FTPWare\\COREFTP" nocase wide ascii
    $pass3c = "GlobalSCAPE" nocase fullword wide ascii
    $pass3d = "CuteFTP" nocase fullword wide ascii
    $pass3e = "FileZilla" nocase fullword wide ascii
    $pass3f = "FTP Navigator" nocase wide ascii
    $pass40 = "NavigatorFTP" nocase wide ascii
    $pass41 = "totalcmd" nocase wide ascii
    $pass42 = "ghistler" nocase wide ascii
    $pass43 = "moz_logins" 
    $pass44 = "sqlite3_open"
	
	$logins0000 = "strmemberid="
	$logins0001 = "strpassword"
	$logins0002 = "&account="
	$logins0005 = "strEmail="
	$logins0006 = "strPassword="
	$logins0007 = "strNexonID="
	$logins0008 = "strPassword"
	$logins0009 = "&loginname=df"
	$logins000a = "hanpwd"
	$logins000d = "l_id="
	$logins000e = "l_pwd"
	$logins000f = "mgid_enc2="
	$logins0010 = "mgpwd_enc2"
	$logins0011 = "GET /login/"
	$logins0012 = "User_ID="
	$logins0013 = "&npw1"
	$logins0014 = "jumin2="
	$logins0015 = "wbUserid="
	$logins0016 = "&wbPasswd"
	$logins0017 = "strNexonID="
	$logins0018 = "strPassword"
	$logins0019 = "txtLoginName="
	$logins001a = "txtPassword"
	$logins001b = "strmemberid="
	$logins001c = "strpassword="
	$logins001d = "&login="
	$logins0021 = "uname="
	$logins0023 = "&Email="
	$logins0024 = "&Passwd"
	$logins0025 = "acctname="
	$logins0026 = "&passwd"
	$logins0028 = "&pass"
	$logins0029 = "&email="
	$logins002a = "&password"
	$logins002b = "&mail="
	$logins002d = "&pass="
	$logins002e = "internet banking" nocase
    $logins002f = "account overview" nocase
    $logins0030 = "viewstatement" nocase
    $logins0031 = "account balance" nocase
    $logins0032 = "available balance" nocase
    $logins0034 = "qzpassword" nocase
    $logins0035 = "accountnumber" nocase
    $logins0036 = "pinnumber" nocase
    $logins0037 = "tannumber" nocase
    $logins0038 = "logontextbox" nocase
    $logins0039 = "internetBanking" nocase
    $logins003a = "AccountDetails" nocase
    $logins003b = "balance details" nocase
    $logins003c = "bank accounts" nocase
    $logins003d = "security questions" nocase
    $logins003e = "Web Cashplus" nocase
    $logins003f = "injtoken" nocase
    $logins0040 = "cash management" nocase
    $logins0041 = "American Express" nocase
    $logins0042 = "Mastercard" nocase fullword
    $logins0043 = "Login confirmation" nocase
    $logins0044 = "activate your account" nocase
    $logins0045 = "wrong password" nocase
    $logins0046 = "UIN#" nocase
    $logins0047 = "login_email" 
    $logins0048 = "txtAccountNumber" 
    $logins0049 = "ecurityPin" 
    $logins004a = "sortCode" 
    $logins004b = "memorableAnswer" 
    $logins004c = "txtCustomerID" 
    $logins004d = "MBindexuserkey"
    $logins004e = "ctlLoginFirstStep"
    $logins004f = "__IDV_URL=hsbc.MyHSBC" 
    $logins0050 = "SignInWelcome"
    $logins0051 = "nputuserid" 
    $logins0052 = "PwdPad=IfYouAreReadingThis" 
    $logins0053 = "txtLoginPin" 
    $logins0054 = "inputmemorable"
    $logins0055 = "UserId1="
	$bank0000 = ".bcvs.ch"
	$bank0001 = ".dbs.com"
	$bank0002 = ".directnet.com"
	$bank0003 = ".inetbank.net.au"
	$bank0004 = ".netbanking.ch"
	$bank0005 = "adambanking.com"
	$bank0006 = "advisernet.com.au"
	$bank0007 = "alpha.gr"
	$bank0008 = "amp.com.au"
	$bank0009 = "apobank.de"
	$bank000a = "baloise.ch"
	$bank000b = "bam.it"
	$bank000c = "bancatoscana.it"
	$bank000d = "bancocaixageral.es"
	$bank000e = "bank.ubs.com"
	$bank000f = "bankatlantic.web-access.com"
	$bank0010 = "banking.bankofscotland.co.uk"
	$bank0011 = "banking.co.at"
	$bank0012 = "bankofcyprus.gr"
	$bank0013 = "bankofthewest.com"
	$bank0014 = "bbva.es"
	$bank0015 = "bbvanetoffice.com"
	$bank0016 = "bcge.ch"
	$bank0017 = "bonline.co.uk"
	$bank0018 = "boq.com.au"
	$bank0019 = "businesse-cashmanager.web-access.com"
	$bank001a = "caixagirona.es"
	$bank001b = "capitalone.com"
	$bank001c = "capitalonesavings.co.uk"
	$bank001d = "cashproweb.com"
	$bank001e = "cbbusinessonline.com"
	$bank001f = "citibank.ae"
	$bank0020 = "citibank.co.uk"
	$bank0021 = "citibank.com"
	$bank0022 = "citibank.com.au"
	$bank0023 = "citibank.com.ph"
	$bank0024 = "citibank.de"
	$bank0025 = "citibusinessonline.da-us.citibank.com"
	$bank0026 = "commercial.wachovia.com"
	$bank0027 = "cortalconsors.de"
	$bank0028 = "csebo.it"
	$bank0029 = "cua.com.au"
	$bank002a = "direct.53.com"
	$bank002b = "dollarbank.com"
	$bank002c = "ebank.emporiki.gr"
	$bank002d = "ebanking-services.com"
	$bank002e = "ebanking.millenniumbank.gr"
	$bank002f = "esgc.com"
	$bank0030 = "express.53.com"
	$bank0031 = "fbmedirect.com"
	$bank0032 = "haspa.de"
	$bank0033 = "homebank.nbg.gr"
	$bank0034 = "icicibank.co.uk"
	$bank0035 = "internet-banking.dbs.com.sg"
	$bank0036 = "laiki.com"
	$bank0037 = "lasallebank.com"
	$bank0038 = "mps.it"
	$bank0039 = "npbs.co.uk"
	$bank003a = "onlineservices.wachovia.com"
	$bank003b = "paco.cabel.it"
	$bank003c = "paypal.com"
	$bank003d = "postbank.de"
	$bank003e = "postfinance.ch"
	$bank003f = "probanx.net"
	$bank0040 = "raiffeisendirect.ch"
	$bank0041 = "reuschel.com"
	$bank0042 = "sanostra.es"
	$bank0043 = "sarasin.ch"
	$bank0044 = "sparkasse-bgl.de"
	$bank0045 = "sparkasse-nienburg.de"
	$bank0046 = ".suntrust.com"
	$bank0047 = "treasury.wamu.com"
	$bank0048 = "ubp.ch"
	$bank0049 = "ubs.com"
	$bank004a = "uno-e.com"
	$bank004b = "usb.com.cy"
	$bank004c = "vip.lasallebank.com"
	$bank004d = "vontobel.com"
	$bank004e = "wachovia.com"
	$bank0050 = "winbank.gr"
	$bank0051 = "www.53.com"
	$bank0052 = "zkb.ch"
	$bank0053 = "access.imb.com.au"
	$bank0054 = "accounts.key.com"
	$bank0055 = "achpayments.wachovia.com"
	$bank0056 = "areasegura.banif.es"
	$bank0057 = "bancae.bancoetcheverria.es"
	$bank0058 = "bank.netbanking.ch"
	$bank0059 = "banking..ch"
	$bank005a = "banking..de"
	$bank005b = "banking.apobank.de"
	$bank005c = "banking.bankofscotland.co.uk"
	$bank005d = "banking.bekb.ch"
	$bank005e = "banking.dkb.de"
	$bank005f = "banking.firsttennessee."
	$bank0060 = "banking.sparda.de"
	$bank0061 = "banking.uboc.com"
	$bank0062 = "banking.us.hsbc.com"
	$bank0063 = "bankingportal..de"
	$bank0064 = "banknet.columbiariverbank.com"
	$bank0065 = "bbvanetoffice.com"
	$bank0066 = "carenet.fnfismd.com"
	$bank0068 = "cib.ibanking-services.com"
	$bank0069 = "citibusinessonline.da-us.citibank.com"
	$bank006b = "corporate-internet-banking.dbs.com"
	$bank006c = "ctm.53.com"
	$bank006d = "dealonline.dbs.com"
	$bank006f = "e-banking.bcvs.ch"
	$bank0070 = "easylink.bankofbermuda.com"
	$bank0071 = "ebank.emporiki.gr"
	$bank0072 = "ebanker.arabbank.com.au"
	$bank0073 = "ebusiness.arabbank.ch"
	$bank0074 = ".openbank.com"
	$bank0075 = "essg.wachovia.com"
	$bank0076 = "etimebanker.bankofthewest.com"
	$bank0077 = "express.53.com"
	$bank0078 = "express.53.com"
	$bank0079 = "finanzportal.fiducia.de"
	$bank007a = "global1.onlinebank.com"
	$bank007b = "hbcibanking.apobank.de"
	$bank007c = "hbnet.cedacri.it"
	$bank007d = "home.cbonline.co.uk"
	$bank007e = "homebank.nbg.gr"
	$bank007f = "homebanking.cariparma.it"
	$bank0080 = "ib.bigsky.net.au"
	$bank0081 = "ib.national.com.au"
	$bank0082 = "ibank.anbusiness.com"
	$bank0083 = ".barclays.co.uk"
	$bank0084 = "ibank.cahoot.com"
	$bank0085 = "ibank.communityfirst.com.au"
	$bank0086 = "inba.lukb.ch"
	$bank0087 = "internet-banking.dbs.com.sg"
	$bank0088 = "internetbanking.gad.de"
	$bank0089 = "is2.cuviewpoint.net"
	$bank008a = "lbbwebclient.lehmanbank.com"
	$bank008b = "lo.lacaixa.es"
	$bank008c = "mcw.airforcefcu.com"
	$bank008d = "mfasa.chase.com"
	$bank008e = "mijn.postbank.nl"
	$bank0090 = "my.hypovereinsbank.de"
	$bank0091 = "my.screenname.aol.com"
	$bank0092 = "myonlineaccounts.abbeynational.co.uk"
	$bank0093 = "net.kutxa.net"
	$bank0094 = "oi.cajamadrid.es"
	$bank0095 = "oie.cajamadridempresas.es"
	$bank0096 = "okd5199.bcge.ch"
	$bank0097 = "onba.zkb.ch"
	$bank0098 = ".lloydstsb.co.uk"
	$bank0099 = "online.bankofcyprus.com"
	$bank009a = "online.bulbank.bg"
	$bank009b = "online.citibank.com"
	$bank009c = "online.mecu.com.au"
	$bank009d = "online.sainsburysbank.co.uk"
	$bank009e = "online.wamu.com"
	$bank009f = ".wellsfargo.com"
	$bank00a0 = "online.westpac.com.au"
	$bank00a1 = "onlineaccess.ncsecu.org"
	$bank00a3 = "onlinebanking.bankofoklahoma.com"
	$bank00a4 = "onlinebanking.capitalone.com"
	$bank00a5 = "onlinebanking.lasallebank.com"
	$bank00a6 = "onlinebanking.nationalcity.com"
	$bank00a7 = "onlineservices.amp.com.au"
	$bank00a8 = "onlineservices.wachovia.com"
	$bank00a9 = "onlineteller.cu.com.au"
	$bank00aa = "paylinks.cunet.org"
	$bank00ab = "portal.izb.de"
	$bank00ac = "portal..de"
	$bank00ad = "secure.accu.com.au"
	$bank00ae = "secure.alpha.gr"
	$bank00af = "secure.ampbanking.com"
	$bank00b0 = ".lloydstsb.com"
	$bank00b1 = "secure.esanda.com"
	$bank00b2 = "secure.tcfexpress.com"
	$bank00b3 = "seguro.cam.es"
	$bank00b4 = "service.oneaccount.com"
	$bank00b5 = "servizi.allianzbank.it"
	$bank00b6 = "servizi.atime.it"
	$bank00b7 = "signin.ebay.com"
	$bank00b8 = "bankofamerica.com"
	$bank00b9 = "sobanet.baloise.ch"
	$bank00ba = "ssl2.haspa.de"
	$bank00bb = "sso.uboc.com"
	$bank00bc = "tb.raiffeisendirect.ch"
	$bank00bd = "tcfexpressbusiness.com"
	$bank00be = "telebanking.hbl.ch"
	$bank00bf = "telemarch.bancamarch.es"
	$bank00c0 = "treasury.wamu.com"
	$bank00c1 = "trust.firsttennessee.com"
	$bank00c2 = "vs.absa.co.za"
	$bank00c3 = "wc.wachovia.com"
	$bank00c4 = "web.da-us.citibank.com"
	$bank00c5 = "webbanking.comerica.com"
	$bank00c6 = "webcmpr.bancopopular.com"
	$bank00c7 = ".co-operativebank.co.uk"
	$bank00c8 = ".smile.co.uk"
	$bank00c9 = ".440strand.com"
	$bank00ca = ".bancopopular.es"
	$bank00cb = ".fiibg.com"
	$bank00cc = ".usbank.com"
	$bank00cd = ".53.com"
	$bank00ce = ".asia.citibank.com"
	$bank00cf = ".bancatoscana.it"
	$bank00d0 = ".banking.co.at"
	$bank00d1 = ".halifax-online.co.uk"
	$bank00d2 = ".bv-i.bancodevalencia.es"
	$bank00d3 = ".caixacatalunya.es"
	$bank00d4 = ".cajacanarias.es"
	$bank00d5 = ".cbbusinessonline.com"
	$bank00d6 = ".citibank.com.au"
	$bank00d7 = ".citibank.com.my"
	$bank00d8 = ".citibank.com.ph"
	$bank00d9 = ".citibank.com.sg"
	$bank00da = ".citibank.de"
	$bank00db = ".citibankonline.ca"
	$bank00dc = ".csebanking.it"
	$bank00dd = ".ebank.us.hsbc.com"
	$bank00de = ".etradeaustralia.com.au"
	$bank00df = ".eurobank.gr"
	$bank00e0 = ".fibanc.es"
	$bank00e1 = ".firstib.com"
	$bank00e2 = ".hellenicbank.com"
	$bank00e3 = ".homebank.com.au"
	$bank00e4 = ".in-bank.net"
	$bank00e5 = ".inversis.com"
	$bank00e6 = ".isideonline.it"
	$bank00e7 = ".jpmorganinvest.com"
	$bank00e8 = ".laiki.com"
	$bank00e9 = ".linksimprese.sanpaoloimi.com"
	$bank00ea = ".mybank.alliance-leicester.co.uk"
	$bank00eb = ".mybusinessbank.co.uk"
	$bank00ec = ".nextbanking.it"
	$bank00ed = ".nwolb.com"
	$bank00ee = ".ocfcu.org"
	$bank00ef = ".onlinesefcu.com"
	$bank00f0 = ".rbsdigital.com"
	$bank00f1 = ".selectbenefit.com"
	$bank00f2 = ".sharebuilder.com"
	$bank00f3 = ".sparkasse.at"
	$bank00f4 = ".ubs.com"
	$bank00f5 = ".usaa.com"
	$bank00f6 = ".winbank.gr"
	$bank00f7 = ".maxisloans.com.au"
	$bank00f8 = ".citizensbankonline.com"
	$bank00f9 = ".site-secure.com"
	$bank00fa = ".commbank.com.au"
	$bank00fb = ".ameritrade.com"
	$bank00fc = "swedbank.com"
    $bank00fd = "hanza.net"
    $bank00fe = "hansa.lt"
    $bank00ff = "swedbankas.lt"
    $bank0100 = "swedbank.net"
    $bank0101 = "bbvapanama.com"
    $bank0102 = "banconal.com.pa"
    $bank0103 = "banconal.com"
    $bank0104 = "banvivienda.net"
    $bank0105 = "banvivienda.com"
    $bank0106 = "bancouno.com.pa"
    $bank0107 = "bancouno.com"
    $bank0108 = "credicorpbank.com"
    $bank0109 = "globalbank.com.pa"
    $bank010a = "globalbank.com"
    $bank010b = "swedbank.lt"
    $bank010c = "hsbc.com.pa"
    $bank010d = "multibank.com"
    $bank010e = "credicorpbank.com"
    $bank010f = "multibank.com.pa"
    $bank0110 = "bbvapanama.com"
    $bank0111 = "banconal.com.pa"
    $bank0112 = "banvivienda.net"
    $bank0113 = "banvivienda.com"
    $bank0114 = "globalbank.com.pa"
    $bank0115 = "globalbank.com"
    $bank0116 = "bancouno.com.pa"
    $bank0117 = "bancouno.com"
    $bank0118 = "banconal.com"
    $bank0119 = "bancopanama.com.pa"
    $bank011a = "bancopanama.com"
    $bank011b = "parex.lt"
    $bank011c = "kiwibank.co.nz"
    $bank011d = "kiwibank.com"
    $bank011e = "seb.lt"
    $bank011f = "kfh.com"
    $bank0120 = "kfh.com.kw"
    $bank0121 = "boq.com"
    $bank0122 = "boq.com.au"
    $bank0123 = "bankofqueensland.com"
    $bank0124 = "asb.co.nz"
    $bank0125 = "asb.com"
    $bank0126 = "tsb.co.nz"
    $bank0127 = "tsb.com"
    $bank0128 = "cahoot.com"
    $bank0129 = "cahoot.co.uk"
    $bank012a = ".ameriprise.com"
    $bank012b = ".ebay.com"
    $bank012c = ".e-gold.com"
    $bank012d = ".tdcanadatrust.com"
    $bank012e = ".banesto.es"
    $bank012f = ".gruposantander.es"
    $bank0130 = ".bancajaproximaempresas.com"
    $bank0131 = ".procreditbank.bg"
    $bank0132 = ".barclays.com"
    $bank0133 = ".dab-bank.com"
    $bank0134 = ".hsbc.co.uk"
    $bank0135 = ".ybonline.co.uk"
    $bank0136 = ".bancoherrero.com"
    $bank0137 = ".bancopastor.es"
    $bank0138 = ".cajamurcia.es"
    $bank0139 = ".caja-granada.es"
    $bank013a = ".fibancmediolanum.es"
    $bank013b = ".cajarioja.es"
    $bank013c = ".cajasoldirecto.es"
    $bank013d = ".caixalaietana.es"
    $bank013e = "areasegura.banif.es"
    $bank013f = ".bgnetplus.com"
    $bank0140 = ".caixagirona.es"
    $bank0141 = ".unicaja.es"
    $bank0142 = ".sabadellatlantico.com"
    $bank0143 = ".cajabadajoz.es"
    $bank0144 = ".banesto.es"
    $bank0145 = ".elmonte.es"
    $bank0146 = ".cajamadridempresas.es"
    $bank0147 = ".gruppocarige.it"
    $bank0148 = "bancopostaonline.poste.it"
    $bank0149 = ".internetbanking.bancaintesa.it"
    $bank014a = "hb.quiubi.it"
    $bank014b = ".iwbank.it"
    $bank014c = "web.secservizi.it"
    $bank014d = "scrigno.popso.it"
    $bank014e = "light.webmoney.ru"
    $bank014f = ".nationet.com"
    $bank0150 = ".banking.first-direct.com"
    $bank0151 = "cardsonline-consumer.com"
    $bank0152 = "internetbanking.aib.ie"
    $bank0153 = "lot-port.bcs.ru"
    $bank0154 = "rupay.com"
    $bank0155 = "ingbank.pl" nocase
    $bank0156 = "millenet.pl" nocase
    $bank0157 = "bph.pl" nocase
    $bank0158 = "centrum24.pl" nocase
    $bank0159 = "nationwide.co.uk" nocase
    $bank015a = "mbank.pl" nocase
    $bank015b = "mbank.com.pl" nocase
    $bank015c = "deutsche-bank.de" nocase
    $bank015d = "bankingportal.kreissparkasse-heilbronn.de" nocase
    $bank015e = "bankingportal.sparkasse-meschede.de" nocase
    $bank015f = "bankingportal.swn-online.de" nocase
    $bank0160 = "bankingportal.sparkasse-aachen.de" nocase
    $bank0161 = "natwest" nocase
    $bank0166 = "e-bullion" nocase
    $bank0167 = "login.hsbc.com" nocase
    $bank0168 = "gemoney" nocase
    $bank0169 = "webid2.gs.com" nocase
    $bank016a = "myworld.insinger.com" nocase
    $bank016b = "my.if.com" nocase
    $bank016c = "leedscitycreditunion.co.uk" nocase
    $bank016d = "libbackoffice.com" nocase
    $bank016e = "clearstream.com" nocase
    $bank016f = "financepilot-trans.mlp.de" nocase
    $bank0170 = "fidelity.co.uk" nocase
    $bank0171 = "selftrade.co.uk" nocase
    $bank0172 = "standardlife.com" nocase
    $bank0173 = "https://www.rbsdigital.com/default.aspx" nocase
    $bank0174 = "https://www.hsbc.co.uk/" nocase
    $bank0175 = "login.live.com" nocase
    $bank0176 = "google.com/accounts/servicelogin" nocase
    $bank0177 = "yahoo.com/config" nocase
    $bank0178 = ".idsonline.com" nocase
    $bank0179 = ".ctn.independent.co.za" nocase
    $bank017a = ".electric.co.za" nocase
    $bank017b = ".rmb.co.za" nocase
    $bank017c = ".great-china.net" nocase
    $bank017d = ".hangseng.com" nocase
    $bank017e = ".hsbcgroup.com" nocase
    $bank017f = ".iba.com.hk" nocase
    $bank0180 = ".bdni.com" nocase
    $bank0181 = ".bii.co.id" nocase
    $bank0182 = ".servitia.com" nocase
    $bank0183 = ".indoweb.com" nocase
    $bank0184 = ".sphere.ad.jp" nocase
    $bank0185 = ".infoweb.or.jp" nocase
    $bank0186 = ".ltcb.co.jp" nocase
    $bank0187 = ".csweb.co.jp" nocase
    $bank0188 = ".ahli.com" nocase
    $bank0189 = ".iworld.net" nocase
    $bank018a = ".cbk.co.kr" nocase
    $bank018b = ".wisedb.co.kr" nocase
    $bank018c = ".cybernet.co.kr" nocase
    $bank018d = ".dacom.co.kr" nocase
    $bank018e = ".kol.co.kr" nocase
    $bank018f = ".kfb.co.kr" nocase
    $bank0190 = ".nacf.co.kr" nocase
    $bank0191 = ".saradar.com.lb" nocase
    $bank0192 = ".bnm.gov.my" nocase
    $bank0193 = ".jaring.my" nocase
    $bank0194 = ".bpi.com.ph" nocase
    $bank0195 = ".pcib.com" nocase
    $bank0196 = ".anb.com.sa" nocase
    $bank0197 = ".isdb.org" nocase
    $bank0198 = ".citicorp.com" nocase
    $bank0199 = ".technet.sg" nocase
    $bank019a = ".chinatrust.com.tw" nocase
    $bank019b = ".bot.or.th" nocase
    $bank019c = ".ntb.co.th" nocase
    $bank019d = ".scb.co.th" nocase
    $bank019e = ".creditandorra.ad" nocase
    $bank019f = ".bawag.com" nocase
    $bank01a0 = ".hypo-alpe-adria.com" nocase
    $bank01a1 = ".kaerntnersparkasse.co.at" nocase
    $bank01a2 = ".hypotirol.at" nocase
    $bank01a3 = ".oenb.co.at" nocase
    $bank01a4 = ".psk.co.at" nocase
    $bank01a5 = ".wpf.at" nocase
    $bank01a6 = ".geocitdies.com" nocase
    $bank01a7 = ".stmk.raiffeisen.at" nocase
    $bank01a8 = ".bkkallincl.co.at" nocase
    $bank01a9 = ".rbs.co.at" nocase
    $bank01aa = ".rlb-tirol.at" nocase
    $bank01ab = ".raiffeisen.at" nocase
    $bank01ac = ".sparkasseleoben.at" nocase
    $bank01ad = ".smw.at" nocase
    $bank01ae = ".sparkasse-weiz.at" nocase
    $bank01af = ".weinviertler-spk.at" nocase
    $bank01b0 = ".bbl.be" nocase
    $bank01b1 = ".cger.be" nocase
    $bank01b2 = ".cbe.be" nocase
    $bank01b3 = ".banque-cortal.fr" nocase
    $bank01b4 = ".fortis.com" nocase
    $bank01b5 = ".iccs.acad.bg" nocase
    $bank01b6 = ".rzb.co.at" nocase
    $bank01b7 = ".centraleurope.com" nocase
    $bank01b8 = ".vol.cz" nocase
    $bank01b9 = ".koba.cz" nocase
    $bank01ba = ".union.cz" nocase
    $bank01bb = ".rzb.co.at" nocase
    $bank01bc = ".addgr.com" nocase
    $bank01bd = ".open.hr" nocase
    $bank01be = ".kaptol.hr" nocase
    $bank01bf = ".pbz.hr" nocase
    $bank01c0 = ".rzb.co.at" nocase
    $bank01c1 = ".enterprise.net" nocase
    $bank01c2 = ".ebs.ie" nocase
    $bank01c3 = ".sda.dk" nocase
    $bank01c4 = ".eyp.ee" nocase
    $bank01c5 = ".depo.ee" nocase
    $bank01c6 = ".forex.ee" nocase
    $bank01c7 = ".aktia.fi" nocase
    $bank01c8 = ".fuib.com" nocase
    $bank01c9 = ".ucb.crimea.ua" nocase
    $bank01ca = ".tcmb.gov.tr" nocase
    $bank01cb = ".osmanli.com.tr" nocase
    $bank01cc = ".falkenbergs-sparb.se" nocase
    $bank01cd = ".stadshypotek.se" nocase
    $bank01ce = ".abnamro.se" nocase
    $bank01cf = ".sb-koper.si" nocase
    $bank01d0 = ".bsi.si" nocase
    $bank01d1 = ".basl.sk" nocase
    $bank01d2 = ".slsp.sk" nocase
    $bank01d3 = ".rzb.co.at" nocase
    $bank01d4 = ".bancpost.ro" nocase
    $bank01d5 = ".kappa.ro" nocase
    $bank01d6 = ".bdk.lublin.pl" nocase
    $bank01d7 = ".pbks.pl" nocase
    $bank01d8 = ".ben.com.pl" nocase
    $bank01d9 = ".bswek.comew.pl" nocase
    $bank01da = ".pbks.pl" nocase
    $bank01db = ".cyf-kr.edu.pl" nocase
    $bank01dc = ".oslonett.no" nocase
    $bank01dd = ".sn.no" nocase
    $bank01de = ".kreditkassen.no" nocase
    $bank01df = ".novit.no" nocase
    $bank01e0 = ".novit.no" nocase
    $bank01e1 = ".novit.no" nocase
    $bank01e2 = ".smn.no" nocase
    $bank01e3 = ".novit.no" nocase
    $bank01e4 = ".novit.no" nocase
    $bank01e5 = ".megabyte.net" nocase
    $bank01e6 = ".bcee.lu" nocase
    $bank01e7 = ".creditlyonnais.lu" nocase
    $bank01e8 = ".innet.net" nocase
    $bank01e9 = ".kbl.lu" nocase
    $bank01ea = ".bil.lu" nocase
    $bank01eb = ".banqueucl.lu" nocase
    $bank01ec = ".swconsult.ch" nocase
    $bank01ed = ".llb.li" nocase
    $bank01ee = ".lanet.lv" nocase
    $bank01ef = ".rbu.vernet.lv" nocase
    $bank01f0 = ".lain.bkc.lv" nocase
    $bank01f1 = ".parexnet.lv" nocase
    $bank01f2 = ".tkb.lv" nocase
    $bank01f3 = ".dlb.bkc.lv" nocase
    $bank01f4 = ".mkb.hu" nocase
    $bank01f5 = ".tke.gr" nocase
    $bank01f6 = ".etba.gr" nocase
    $bank01f7 = ".kapatel.gr" nocase
    $bank01f8 = ".tinet.ch" nocase
    $bank01f9 = ".tinet.ch" nocase
    $bank01fa = ".juliusbaer.com" nocase
    $bank01fb = ".vontobel.ch" nocase
    $bank01fc = ".bcf.ch" nocase
    $bank01fd = ".bgl.ch" nocase
    $bank01fe = ".hottinger.com" nocase
    $bank01ff = ".cogeba.ch" nocase
    $bank0200 = ".mbczh.ch" nocase
    $bank0201 = ".swconsult.ch" nocase
    $bank0202 = ".ska.com" nocase
    $bank0203 = ".tgkb.ch" nocase
    $bank0204 = ".urkb.ch" nocase
    $bank0205 = ".zhkb.ch" nocase
    $bank0206 = ".bnu.pt" nocase
    $bank0207 = ".bpatlantico.pt" nocase
    $bank0208 = ".bcf.pt" nocase
    $bank0209 = ".bes.pt" nocase
    $bank020a = ".banif.pt" nocase
    $bank020b = ".barclays.pt" nocase
    $bank020c = ".cgd.pt" nocase
    $bank020d = ".cisf.pt" nocase
    $bank020e = ".mayo-ireland.ie" nocase
    $bank020f = ".webnet.ie" nocase
    $bank0210 = ".365online.com" nocase
    $bank0211 = ".ebs.ie" nocase
    $bank0212 = ".bga.it" nocase
    $bank0213 = ".carige.it" nocase
    $bank0214 = ".bci.it" nocase
    $bank0215 = ".bcoopimola.it" nocase
    $bank0216 = ".lavalsabbina.it" nocase
    $bank0217 = ".bcc.it" nocase
    $bank0218 = ".bcccst.it" nocase
    $bank0219 = ".val.it" nocase
    $bank021a = ".bcc.cremonese.it" nocase
    $bank021b = ".ets.it" nocase
    $bank021c = ".net1.it" nocase
    $bank021d = ".agrobresciano.it" nocase
    $bank021e = ".bccbarlassina.com" nocase
    $bank021f = ".bcc.it" nocase
    $bank0220 = ".bcc.carugate.mi.it" nocase
    $bank0221 = ".diel.it" nocase
    $bank0222 = ".bccgarda.numerica.it" nocase
    $bank0223 = ".romagna.com" nocase
    $bank0224 = ".bccfiuggi.it" nocase
    $bank0225 = ".bcc.it" nocase
    $bank0226 = ".bccsgv.it" nocase
    $bank0227 = ".media.it" nocase
    $bank0228 = ".bccsanteramo.it" nocase
    $bank0229 = ".bcctriuggio.it" nocase
    $bank022a = ".bccvdc.it" nocase
    $bank022b = ".bccfc.it" nocase
    $bank022c = ".bga.it" nocase
    $bank022d = ".biemmepro.it" nocase
    $bank022e = ".bnl.it" nocase
    $bank022f = ".bpam.it" nocase
    $bank0230 = ".bpci.it" nocase
    $bank0231 = ".bpf.it" nocase
    $bank0232 = ".bplazio.it" nocase
    $bank0233 = ".popvoba.it" nocase
    $bank0234 = ".bpa.it" nocase
    $bank0235 = ".bpb.it" nocase
    $bank0236 = ".meda.it" nocase
    $bank0237 = ".poplodi.it" nocase
    $bank0238 = ".bpm.it" nocase
    $bank0239 = ".bpn.it" nocase
    $bank023a = ".bpb.it" nocase
    $bank023b = ".bpv.it" nocase
    $bank023c = ".xnet.it" nocase
    $bank023d = ".popvi.it" nocase
    $bank023e = ".bpci.it" nocase
    $bank023f = ".bsp.it" nocase
    $bank0240 = ".ambro.it" nocase
    $bank0241 = ".bancodisicilia.it" nocase
    $bank0242 = ".cariverona.it" nocase
    $bank0243 = ".crtn.it" nocase
    $bank0244 = ".caribusiness.it" nocase
    $bank0245 = ".sgol.it" nocase
    $bank0246 = ".crcarpi.it" nocase
    $bank0247 = ".romagna.com" nocase
    $bank0248 = ".caricast.it" nocase
    $bank0249 = ".paginegialle.it" nocase
    $bank024a = ".crimola.it" nocase
    $bank024b = ".arcanet.it" nocase
    $bank024c = ".cariprpc.pr.it" nocase
    $bank024d = ".caripisa.it" nocase
    $bank024e = ".iper.net" nocase
    $bank024f = ".omniway.sm" nocase
    $bank0250 = ".carisa.it" nocase
    $bank0251 = ".carispe.it" nocase
    $bank0252 = ".start.it" nocase
    $bank0253 = ".cassalombarda.it" nocase
    $bank0254 = ".cracantu.it" nocase
    $bank0255 = ".cracastelgoffredo.it" nocase
    $bank0256 = ".crbvfbcc.it" nocase
    $bank0257 = ".sunrise.it" nocase
    $bank0258 = ".well.it" nocase
    $bank0259 = ".delta.it" nocase
    $bank025a = ".ruralerovereto.it" nocase
    $bank025b = ".crsbc.it" nocase
    $bank025c = ".cassamarca.it" nocase
    $bank025d = ".creberg.it" nocase
    $bank025e = ".credit.it" nocase
    $bank025f = ".bnl.it" nocase
    $bank0260 = ".bcc.it" nocase
    $bank0261 = ".ipacri.it" nocase
    $bank0262 = ".mbres.it" nocase
    $bank0263 = ".mediocredito.fvg.it" nocase
    $bank0264 = ".medioumbria.it" nocase
    $bank0265 = ".mfc.it" nocase
    $bank0266 = ".mediolanum.it" nocase
    $bank0267 = ".nbctkb.it" nocase
    $bank0268 = ".1822direkt.com" nocase
    $bank0269 = ".adig.de" nocase
    $bank026a = ".americanexpress.de" nocase
    $bank026b = ".maffei.de" nocase
    $bank026c = ".bkm.de" nocase
    $bank026d = ".schwaebisch-hall.de" nocase
    $bank026e = ".bbs-sachsen.de" nocase
    $bank026f = ".comdirect.de" nocase
    $bank0270 = ".dbresearch.com" nocase
    $bank0271 = ".dit.de" nocase
    $bank0272 = "pekao24.pl" nocase
    $bank0273 = ".gallinat.de" nocase
    $bank0274 = ".heimstatt.de" nocase
    $bank0275 = ".essenhyp.de" nocase
    $bank0276 = ".lrp.de" nocase
    $bank0277 = ".lbs-hamburg.de" nocase
    $bank0278 = ".lbs-wuertt.de" nocase
    $bank0279 = ".leonberger.de" nocase
    $bank027a = ".lhb.de" nocase
    $bank027b = ".nordlb.de" nocase
    $bank027c = ".olb.de" nocase
    $bank027d = ".raiba-beilngries.de" nocase
    $bank027e = ".dresdner-rb.kontodirekt.de" nocase
    $bank027f = ".rberding.de" nocase
    $bank0280 = ".rb-eschlkam-neukirchen.de" nocase
    $bank0281 = ".raiba-fluorn-winzeln.rwg.de" nocase
    $bank0282 = ".rb-frankenhardt-stimpfach.de" nocase
    $bank0283 = ".rbgarrel.de" nocase
    $bank0284 = ".rb-graefo.de" nocase
    $bank0285 = ".rbk-haag-gars.de" nocase
    $bank0286 = ".raiba-haibach.de" nocase
    $bank0287 = ".raiba-hoes.de" nocase
    $bank0288 = ".raiba-ichenhausen.de" nocase
    $bank0289 = ".direktpro.com" nocase
    $bank028a = ".rb-ismaning.de" nocase
    $bank028b = ".rb-kimi.de" nocase
    $bank028c = ".raiba-moembris.de" nocase
    $bank028d = ".raiba-neuler.rwg.de" nocase
    $bank028e = ".rb-nordspessart-freigericht.de" nocase
    $bank028f = ".raibaschleissheim.de" nocase
    $bank0290 = ".vb-rb-passau-freyung.de" nocase
    $bank0291 = ".rottaler-raiba.de" nocase
    $bank0292 = ".raiba-regenstauf.de" nocase
    $bank0293 = ".vb-rb-riedlingen.de" nocase
    $bank0294 = ".raiba-sob.de" nocase
    $bank0295 = ".raiba-voba.de" nocase
    $bank0296 = ".rvb-varel-zetel.de" nocase
    $bank0297 = ".sachsenlb.de" nocase
    $bank0298 = ".santander.de" nocase
    $bank0299 = ".socgen.de" nocase
    $bank029a = ".sparda-hh.de" nocase
    $bank029b = ".deka.de" nocase
    $bank029c = ".ksk-alzey.de" nocase
    $bank029d = ".ksk-bernkastel-wittlich.de" nocase
    $bank029e = ".kskcalw.de" nocase
    $bank029f = ".kskcochem-zell.de" nocase
    $bank02a0 = ".sparkasse-ebersberg.de" nocase
    $bank02a1 = ".es.ksk.de" nocase
    $bank02a2 = ".kreissparkasse-heinsberg.de" nocase
    $bank02a3 = ".ksk-koeln.de" nocase
    $bank02a4 = ".kskkusel.de" nocase
    $bank02a5 = ".sparkasse-lichtenfels.de" nocase
    $bank02a6 = ".snet.de" nocase
    $bank02a7 = ".ksk-stade.de" nocase
    $bank02a8 = ".ksk-tuebingen.de" nocase
    $bank02a9 = ".lzo.com" nocase
    $bank02aa = ".osgv.de" nocase
    $bank02ab = ".sparkasse-bad-hersfeld-rotenburg.de" nocase
    $bank02ac = ".sparkasse-radevormwald.de" nocase
    $bank02ad = ".sparkasse-ravensburg.de" nocase
    $bank02ae = ".sparkasse.net" nocase
    $bank02af = ".sparkasse-werra-meissner.de" nocase
    $bank02b0 = ".stadtsparkasse-aichach.de" nocase
    $bank02b1 = ".sskba.de" nocase
    $bank02b2 = "sskduesseldorf.de" nocase
    $bank02b3 = ".sparkasse-magdeburg.de" nocase
    $bank02b4 = ".stadtsparkasse-nuernberg.de" nocase
    $bank02b5 = ".stadtsparkasse-remscheid.de" nocase
    $bank02b6 = ".suedboden.de" nocase
    $bank02b7 = ".vbk-du.de" nocase
    $bank02b8 = ".vb-badfriedrichshall.de" nocase
    $bank02b9 = ".voba-bensheim.de" nocase
    $bank02ba = ".voba-bes-boe.de" nocase
    $bank02bb = ".bischofsheimer-vb.de" nocase
    $bank02bc = ".vb-bocholt.de" nocase
    $bank02bd = ".borkenervb.de" nocase
    $bank02be = ".voba-brv.de" nocase
    $bank02bf = ".vb-brilon.de" nocase
    $bank02c0 = "b-bruchsal.de" nocase
    $bank02c1 = ".vb-ammerland.de" nocase
    $bank02c2 = ".vb-eppingen.de" nocase
    $bank02c3 = ".cymagic.com" nocase
    $bank02c4 = ".mmedia-ge.de" nocase
    $bank02c5 = ".genoba-meckenbeuren.rwg.de" nocase
    $bank02c6 = ".vb-greven.de" nocase
    $bank02c7 = ".voba-gg.de" nocase
    $bank02c8 = ".vb-hamm.de" nocase
    $bank02c9 = ".vbhan.de" nocase
    $bank02ca = ".heidenheimer-voba.de" nocase
    $bank02cb = ".vbu.wgv.de" nocase
    $bank02cc = ".vbketsch.de" nocase
    $bank02cd = ".vb-lahr.de" nocase
    $bank02ce = ".vblehrte.genonord.de" nocase
    $bank02cf = ".voba-main-taunus.de" nocase
    $bank02d0 = ".voba-ober-moerlen.de" nocase
    $bank02d1 = ".vb-reutlingen.de" nocase
    $bank02d2 = ".vb-rheda-wd.de" nocase
    $bank02d3 = ".vb-rhein-wupper.de" nocase
    $bank02d4 = ".vbsauerland.de" nocase
    $bank02d5 = ".vb-spiesen-elversberg.de" nocase
    $bank02d6 = ".vbstadthagen.genonord.de" nocase
    $bank02d7 = ".hellwegeranzeiger.de" nocase
    $bank02d8 = ".vilstal.net" nocase
    $bank02d9 = ".wb-aktuell.com" nocase
    $bank02da = ".vb-wolfratshausen.de" nocase
    $bank02db = ".bristol-west.co.uk" nocase
    $bank02dc = ".cheltglos.co.uk" nocase
    $bank02dd = ".ebrd.com" nocase
    $bank02de = ".ftbni.com" nocase
    $bank02df = ".hdb.co.uk" nocase
    $bank02e0 = ".hsbcib.com" nocase
    $bank02e1 = ".hsbcgroup.com" nocase
    $bank02e2 = ".mhbs.co.uk" nocase
    $bank02e3 = ".natdsionwidde.co.auk" nocase
    $bank02e4 = ".natwest.co.uk" nocase
    $bank02e5 = ".rbos.co.uk" nocase
    $bank02e6 = ".sbil.co.uk" nocase
    $bank02e7 = ".careermosaic.com" nocase
    $bank02e8 = "kb24.pl" nocase
    $bank02e9 = ".abnamro.nl" nocase
    $bank02ea = ".bng.nl" nocase
    $bank02eb = ".friba.nl" nocase
    $bank02ec = ".vanlanschot.nl" nocase
    $bank02ed = ".veronica.nl" nocase
    $bank02ee = ".limbu.nl" nocase
    $bank02ef = ".bmo.com" nocase
    $bank02f0 = ".desjardins.com" nocase
    $bank02f1 = ".canadatrust.com" nocase
    $bank02f2 = ".citizenstrust.ca" nocase
    $bank02f3 = ".coopcb.com" nocase
    $bank02f4 = ".cdb.com.cy" nocase
    $bank02f5 = ".fbme.com" nocase
    $bank02f6 = ".sgcyprus.com" nocase
    $bank02f7 = ".frostbank.com" nocase
    $bank02f8 = ".mibank.com" nocase
    $bank02f9 = ".floridagulfbank.com" nocase
    $bank02fa = ".ebanking-services.com" nocase
    $bank02fb = "commerceonlinebanking.com" nocase
    $bank02fc = ".warwickcreditunion.com.au" nocase
    $bank02fd = ".qccu.com.au" nocase
    $bank02fe = "ib.boq.com.au" nocase
    $bank02ff = "secure.ampbanking.com" nocase
    $bank0300 = "internetbanking.suncorpmetway.com.au" nocase
    $bank0301 = "online.hbs.net.au" nocase
    $bank0302 = "online.mecu.com.au" nocase
    $bank0303 = "amp.com.au" nocase
    $bank0304 = ".tsw.com.au" nocase
    $bank0306 = ".rbsdigital.com" nocase
    $bank0307 = ".netspend.com" nocase
    $bank0308 = ".365online.co.uk" nocase
    $bank0309 = "ibanking.banksa.com.au" nocase
    $bank030b = "ibanking.stgeorge.com.au" nocase
    $bank030c = "westpac.com.au" nocase
    $bank030d = "probanking.procreditbank.bg" nocase
    $bank030e = ".citibank.de" nocase
    $bank030f = "arquia.es" nocase
    $bank0310 = ".uno-e.com" nocase
    $bank0311 = "privati.internetbanking.bancaintesa.it" nocase
    $bank0312 = ".gbw2.it" nocase
    $bank0313 = ".gruppocarige.it" nocase
    $bank0314 = "isideonline.it" nocase
    $bank0315 = "hb.quiubi.it" nocase
    $bank0316 = "mijn.postbank.nl" nocase
    $bank0319 = "kiwibank.co.nz" nocase
    $bank031a = "secure.inteligo.com.pl" nocase
    $bank031b = "inwestoronline.pl" nocase
    $bank031c = "ipko.pl" nocase
    $bank031f = "citibank.ru" nocase
    $bank0320 = "cardsonline-consumer.com" nocase
    $bank0321 = "home.cbonline.co.uk" nocase
    $bank0322 = ".co-operativebank.co.uk" nocase
    $bank0324 = ".banking.first-direct.com/" nocase
    $bank0325 = "halifax-online.co.uk" nocase
    $bank0326 = ".ebank.hsbc.co.uk" nocase
    $bank0329 = "moneybookers.com" nocase
    $bank032a = ".nationet.com" nocase
    $bank032f = "home.ybonline.co.uk" nocase
    $bank0330 = "altergold.com" nocase
    $bank0331 = "chaseonline.chase.com" nocase
    $bank0332 = "c-gold.com" nocase
    $bank0333 = "resources.chase.com" nocase
    $bank0336 = ".us.hsbc.com" nocase

	condition:
	any of them
}