rule bruteforce
{
    meta:
    description = "Indicates attempt to brute force passwords"
    
    strings:
    $br0 = "winpass" fullword nocase
    $br1 = "orainstall" fullword nocase
    $br2 = "sqlpassoainstall" fullword nocase
    $br3 = "db1234" fullword nocase
    $br4 = "databasepassword" fullword nocase
    $br5 = "databasepass" fullword nocase
    $br6 = "dbpassword" fullword nocase
    $br7 = "dbpass" fullword nocase
    $br8 = "domainpassword" fullword nocase
    $br9 = "domainpass" fullword nocase
    $br10 = "exchange" fullword nocase
    $br11 = "loginpass" fullword nocase
    $br12 = "win2000" fullword nocase
    $br13 = "windows" fullword nocase
    $br14 = "oeminstall" fullword nocase
    $br15 = "accounting" fullword nocase
    $br16 = "accounts" fullword nocase
    $br17 = "letmein" fullword nocase
    $br18 = "outlook" fullword nocase
    $br19 = "qwerty" fullword nocase
    $br20 = "temp123" fullword nocase
    $br21 = "default" fullword nocase
    $br22 = "changeme" fullword nocase
    $br23 = "secret" fullword nocase
    $br24 = "payday" fullword nocase
    $br25 = "deadline" fullword nocase
    $br26 = "1234567890" fullword nocase
    $br27 = "123456789" fullword nocase
    $br28 = "12345678" fullword nocase
    $br29 = "1234567" fullword nocase
    $br30 = "123456" fullword nocase
    $br31 = "pass1234" fullword nocase
    $br32 = "passwd" fullword nocase
    $br33 = "password" fullword nocase
    $br34 = "password1" fullword nocase
    $br35 = "admin:" nocase
    $br36 = "admin:123456" nocase
    $br37 = "admin:password" nocase
    $br38 = "admin:admin" nocase
    $br39 = "!root:" nocase
    $br40 = "zxc:cascade" nocase
    $br41 = "11111:x-admin" nocase
    $br42 = "1234:1234" nocase
    $br43 = "1500:and" nocase
    $br45 = "1502:1502" nocase
    $br46 = ":12345" nocase
    $br47 = ":1234admin" nocase
    $br48 = ":3ascotel" nocase
    $br49 = ":4getme2" nocase
    $br50 = ":BRIDGE" nocase
    $br51 = ":Cisco" nocase
    $br52 = ":Intel" nocase
    $br54 = ":SUPER" nocase
    $br56 = ":TANDBERG" nocase
    $br57 = ":TENmanUFactOryPOWER" nocase
    $br58 = ":Telecom" nocase
    $br59 = ":_Cisco" nocase
    $br60 = ":access" nocase
    $br61 = ":admin" nocase
    $br62 = ":ascend" nocase
    $br63 = ":atc123" nocase
    $br64 = ":cisco" nocase
    $br65 = ":connect" nocase fullword
    $br66 = ":default" nocase fullword
    $br67 = ":enter" nocase
    $br68 = ":epicrouter" nocase
    $br69 = ":hs7mwxkk" nocase
    $br70 = ":letmein" nocase
    $br71 = ":medion" nocase
    $br72 = ":nokia" nocase
    $br73 = ":password" nocase fullword
    $br74 = ":pento" nocase
    $br75 = ":public" nocase fullword
    $br76 = ":secret" nocase fullword
    $br77 = ":sitecom" nocase
    $br78 = ":smcadmin" nocase
    $br79 = ":administrator" nocase
    $br80 = ":speedxess" nocase
    $br81 = ":sysadm" nocase
    $br82 = ":system" nocase fullword
    $br83 = "ADMINISTRATOR:ADMINISTRATOR" nocase
    $br84 = "ADMN:admn" nocase
    $br85 = "ADSL:expert03" nocase
    $br86 = "ADVMAIL:HP" nocase
    $br87 = "ADVMAIL:HPOFFICE" nocase
    $br89 = "Admin:" nocase
    $br90 = "Admin:123456" nocase
    $br91 = "Admin:admin" nocase
    $br92 = "Administrator:" nocase
    $br93 = "Administrator:3ware" nocase
    $br94 = "Administrator:admin" nocase
    $br95 = "Administrator:changeme" nocase
    $br96 = "Administrator:ganteng" nocase
    $br97 = "Administrator:password" nocase
    $br98 = "Administrator:pilou" nocase
    $br99 = "Administrator:smcadmin" nocase
    $br100 = "Any:12345" nocase
    $br101 = "CISCO15:otbu+1" nocase
    $br102 = "CSG:SESAME" nocase
    $br103 = "Cisco:Cisco" nocase
    $br104 = "FIELD:HPONLY" nocase
    $br105 = "FIELD:HPP187" nocase
    $br107 = "FIELD:HPWORD" nocase
    $br109 = "FIELD:LOTUS" nocase
    $br110 = "FIELD:MANAGER" nocase
    $br111 = "FIELD:MGR" nocase
    $br112 = "FIELD:SERVICE" nocase
    $br113 = "FIELD:SUPPORT" nocase
    $br114 = "Factory:56789" nocase
    $br115 = "GEN1:gen1" nocase
    $br116 = "GEN2:gen2" nocase
    $br117 = "Gearguy:Geardog" nocase
    $br118 = "HELLO:FIELD.SUPPORT" nocase
    $br119 = "HELLO:MANAGER.SYS" nocase
    $br120 = "HELLO:MGR.SYS" nocase
    $br121 = "HELLO:OP.OPERATOR" nocase
    $br122 = "HTTP:HTTP" nocase
    $br123 = "IntraStack:Asante" nocase
    $br124 = "IntraSwitch:Asante" nocase
    $br125 = "MAIL:HPOFFICE" nocase
    $br126 = "MAIL:MAIL" nocase
    $br127 = "MAIL:MPE" nocase
    $br128 = "MAIL:REMOTE" nocase
    $br129 = "MAIL:TELESUP" nocase
    $br130 = "MANAGER:COGNOS" nocase
    $br131 = "MANAGER:HPOFFICE" nocase
    $br132 = "MANAGER:ITF3000" nocase
    $br133 = "MANAGER:SECURITY" nocase
    $br134 = "MANAGER:SYS" nocase
    $br135 = "MANAGER:TCH" nocase
    $br136 = "MANAGER:TELESUP" nocase
    $br137 = "MDaemon:MServer" nocase
    $br138 = "MGR:CAROLIAN" nocase
    $br139 = "MGR:CCC" nocase
    $br140 = "MGR:CNAS" nocase
    $br141 = "MGR:COGNOS" nocase
    $br142 = "MGR:CONV" nocase
    $br143 = "MGR:HPDESK" nocase
    $br144 = "MGR:HPOFFICE" nocase
    $br145 = "MGR:HPONLY" nocase
    $br146 = "MGR:HPP187" nocase
    $br147 = "MGR:HPP189" nocase
    $br148 = "MGR:HPP196" nocase
    $br149 = "MGR:INTX3" nocase
    $br150 = "MGR:ITF3000" nocase
    $br151 = "MGR:NETBASE" nocase
    $br152 = "MGR:REGO" nocase
    $br153 = "MGR:RJE" nocase
    $br154 = "MGR:ROBELLE" nocase
    $br155 = "MGR:SECURITY" nocase
    $br156 = "MGR:SYS" nocase
    $br157 = "MGR:TELESUP" nocase
    $br158 = "MGR:VESOFT" nocase
    $br159 = "MGR:WORD" nocase
    $br160 = "MGR:XLSERVER" nocase
    $br161 = "MICRO:RSX" nocase
    $br162 = "Manager:" nocase
    $br163 = "Manager:friend" nocase
    $br164 = "NAU:NAU" nocase
    $br165 = "NICONEX:NICONEX" nocase
    $br166 = "OPERATOR:COGNOS" nocase
    $br167 = "OPERATOR:DISC" nocase
    $br168 = "OPERATOR:SUPPORT" nocase
    $br169 = "OPERATOR:SYS" nocase
    $br170 = "OPERATOR:SYSTEM" nocase
    $br171 = "PCUSER:SYS" nocase
    $br172 = "PRODDTA:PRODDTA" nocase
    $br173 = "Polycom:456" nocase
    $br174 = "Polycom:SpIp" nocase
    $br175 = "RMUser1:password" nocase
    $br176 = "RSBCMON:SYS" nocase
    $br177 = "SPOOLMAN:HPOFFICE" nocase
    $br178 = "SSA:SSA" nocase
    $br179 = "SYSADM:sysadm" nocase
    $br180 = "SYSDBA:masterkey" nocase
    $br181 = "Service:5678" nocase
    $br182 = "TMAR#HWMT8007079:" nocase
    $br183 = "USERID:PASSW0RD" nocase
    $br184 = "User:Password" nocase
    $br185 = "WP:HPOFFICE" nocase
    $br186 = "aaa:often" nocase
    $br188 = "admin2:changeme" nocase
    $br189 = "admin:" nocase
    $br190 = "admin:0" nocase
    $br191 = "admin:1111" nocase
    $br192 = "admin:123" nocase
    $br193 = "admin:1234" nocase
    $br194 = "admin:12345" nocase
    $br195 = "admin:123456" nocase
    $br196 = "admin:1234admin" nocase
    $br197 = "admin:2222" nocase
    $br198 = "admin:22222" nocase
    $br199 = "admin:Ascend" nocase
    $br200 = "admin:NetCache" nocase
    $br201 = "admin:NetSurvibox" nocase
    $br202 = "admin:OCS" nocase
    $br203 = "admin:OkiLAN" nocase
    $br204 = "admin:P@55w0rd!" nocase
    $br205 = "admin:Password" nocase
    $br206 = "admin:Protector" nocase
    $br207 = "admin:Sharp" nocase
    $br208 = "admin:access" nocase
    $br209 = "admin:admin" nocase
    $br210 = "admin:admin123" nocase
    $br211 = "admin:administrator" nocase
    $br212 = "admin:adslolitec" nocase
    $br213 = "admin:adslroot" nocase
    $br214 = "admin:articon" nocase
    $br215 = "admin:asante" nocase
    $br216 = "admin:asd" nocase
    $br217 = "admin:atlantis" nocase
    $br218 = "admin:barricade" nocase
    $br219 = "admin:bintec" nocase
    $br220 = "admin:changeme" nocase
    $br221 = "admin:comcomcom" nocase
    $br222 = "admin:default" nocase
    $br223 = "admin:draadloos" nocase
    $br224 = "admin:epicrouter" nocase
    $br225 = "admin:extendnet" nocase
    $br226 = "admin:hagpolm1" nocase
    $br227 = "admin:hello" nocase
    $br228 = "admin:hp.com" nocase
    $br229 = "admin:imss7.0" nocase
    $br230 = "admin:ironport" nocase
    $br231 = "admin:isee" nocase
    $br232 = "admin:leviton" nocase
    $br233 = "admin:linga" nocase
    $br234 = "admin:michelangelo" nocase
    $br235 = "admin:microbusiness" nocase
    $br236 = "admin:motorola" nocase
    $br237 = "admin:mu" nocase
    $br238 = "admin:my_DEMARC" nocase
    $br239 = "admin:netadmin" nocase
    $br240 = "admin:noway" nocase
    $br241 = "admin:operator" nocase
    $br242 = "admin:password" nocase
    $br243 = "admin:passwort" nocase
    $br244 = "admin:pfsense" nocase
    $br245 = "admin:rmnetlm" nocase
    $br246 = "admin:secure" nocase
    $br247 = "admin:setup" nocase
    $br248 = "admin:smallbusiness" nocase
    $br249 = "admin:smcadmin" nocase
    $br250 = "admin:switch" nocase
    $br251 = "admin:symbol" nocase
    $br252 = "admin:synnet" nocase
    $br253 = "admin:sysAdmin" nocase
    $br254 = "admin:w2402" nocase
    $br255 = "admin:x-admin" nocase
    $br256 = "administrator:" nocase
    $br257 = "adminstat:OCS" nocase
    $br258 = "adminstrator:changeme" nocase
    $br259 = "adminttd:adminttd" nocase
    $br260 = "adminuser:OCS" nocase
    $br261 = "adminview:OCS" nocase
    $br262 = "apc:apc" nocase
    $br263 = "cablecom:router" nocase
    $br264 = "cac_admin:cacadmin" nocase
    $br265 = "ccrusr:ccrusr" nocase
    $br266 = "cellit:cellit" nocase
    $br267 = "cisco:" nocase
    $br268 = "citel:password" nocase
    $br269 = "comcast:" nocase
    $br270 = "comcast:1234" nocase
    $br271 = "craft:" nocase
    $br272 = "cusadmin:highspeed" nocase
    $br273 = "customer:none" nocase
    $br274 = "dadmin:dadmin01" nocase
    $br275 = "davox:davox" nocase
    $br276 = "deskalt:password" nocase
    $br277 = "deskman:changeme" nocase
    $br278 = "desknorm:password" nocase
    $br279 = "deskres:password" nocase
    $br280 = "device:device" nocase
    $br281 = "diag:danger" nocase
    $br282 = "disttech:4tas" nocase
    $br283 = "e250:e250changeme" nocase
    $br284 = "e500:e500changeme" nocase
    $br285 = "guest:" nocase
    $br286 = "guest:guest" nocase
    $br287 = "helpdesk:OCS" nocase
    $br288 = "hsa:hsadb" nocase
    $br289 = "images:images" nocase
    $br290 = "install:secret" nocase
    $br291 = "installer:installer" nocase
    $br292 = "intel:intel" nocase
    $br293 = "intermec:intermec" nocase
    $br294 = "isp:isp" nocase
    $br295 = "jagadmin:" nocase
    $br296 = "login:access" nocase
    $br297 = "login:admin" nocase
    $br298 = "m1122:m1122" nocase
    $br299 = "maint:maint" nocase
    $br300 = "maint:ntacdmax" nocase
    $br301 = "manage:!manage" nocase
    $br302 = "manager:admin" nocase
    $br303 = "manager:friend" nocase
    $br304 = "manager:manager" nocase
    $br305 = "manuf:xxyyzz" nocase
    $br306 = "mediator:mediator" nocase
    $br307 = "mlusr:mlusr" nocase
    $br308 = "monitor:monitor" nocase
    $br309 = "mso:w0rkplac3rul3s" nocase
    $br310 = "naadmin:naadmin" nocase
    $br311 = "netadmin:nimdaten" nocase
    $br312 = "netman:" nocase
    $br313 = "netrangr:attack" nocase
    $br314 = "netscreen:netscreen" nocase
    $br315 = "none:0" nocase
    $br316 = "none:admin" nocase
    $br317 = "operator:" nocase
    $br318 = "operator:$chwarzepumpe" nocase
    $br319 = "operator:1234" nocase
    $br320 = "operator:operator" nocase
    $br321 = "patrol:patrol" nocase
    $br322 = "piranha:piranha" nocase
    $br323 = "piranha:q" nocase
    $br324 = "public:" nocase
    $br325 = "public:public" nocase
    $br326 = "radware:radware" nocase
    $br327 = "readonly:lucenttech2" nocase
    $br328 = "readwrite:lucenttech1" nocase
    $br329 = "replicator:replicator" nocase
    $br330 = "root:0P3N" nocase
    $br331 = "root:1234" nocase
    $br332 = "root:12345" nocase
    $br333 = "root:3ep5w2u" nocase
    $br334 = "root:Cisco" nocase
    $br335 = "root:Mau'dib" nocase
    $br336 = "root:admin" nocase
    $br337 = "root:admin_1" nocase
    $br338 = "root:ascend" nocase
    $br339 = "root:attack" nocase
    $br340 = "root:blender" nocase
    $br341 = "root:calvin" nocase
    $br342 = "root:changeme" nocase
    $br343 = "root:davox" nocase
    $br344 = "root:default" nocase
    $br345 = "root:fivranne" nocase
    $br346 = "root:iDirect" nocase
    $br347 = "root:pass" nocase
    $br348 = "root:password" nocase
    $br349 = "root:root" nocase
    $br350 = "root:tslinux" nocase
    $br351 = "rwa:rwa" nocase
    $br352 = "scmadmin:scmchangeme" nocase
    $br353 = "scout:scout" nocase
    $br354 = "security:security" nocase
    $br355 = "service:smile" nocase
    $br356 = "setup:changeme" nocase
    $br357 = "setup:setup" nocase
    $br358 = "smc:smcadmin" nocase
    $br359 = "storwatch:specialist" nocase
    $br360 = "stratacom:stratauser" nocase
    $br361 = "super.super:" nocase
    $br362 = "super.super:master" nocase
    $br363 = "super:5777364" nocase
    $br364 = "super:super" nocase
    $br365 = "superadmin:secret" nocase
    $br366 = "superman:21241036" nocase
    $br367 = "superman:talent" nocase
    $br368 = "superuser:admin" nocase
    $br369 = "supervisor:" nocase
    $br370 = "supervisor:PlsChgMe" nocase
    $br371 = "supervisor:supervisor" nocase
    $br372 = "support:h179350" nocase
    $br373 = "support:support" nocase
    $br374 = "sys:uplink" nocase
    $br375 = "sysadmin:PASS" nocase
    $br376 = "sysadmin:password" nocase
    $br377 = "system:sys" nocase
    $br378 = "manager:change_on_install" nocase
    $br379 = "system:password" nocase
    $br380 = "teacher:password" nocase
    $br381 = "telecom:telecom" nocase
    $br382 = "tellabs:tellabs#1" nocase
    $br383 = "temp1:password" nocase
    $br384 = "tiara:tiaranet" nocase
    $br385 = "tiger:tiger123" nocase
    $br386 = "topicalt:password" nocase
    $br387 = "topicnorm:password" nocase
    $br388 = "topicres:password" nocase
    $br389 = "user:password" nocase
    $br390 = "user:tivonpw" nocase
    $br391 = "user:user" nocase
    $br392 = "vcr:NetVCR" nocase
    $br393 = "vt100:public" nocase
    $br394 = "webadmin:1234" nocase
    $br395 = "webadmin:webadmin" nocase
    $br396 = "websecadm:changeme" nocase
    $br397 = "wlse:wlsedb" nocase
    $br398 = "wradmin:trancell" nocase
    
    condition:
    10 of ($br*)
}